
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Counteronline
{

    public long CounterID { get; set; }

    public int TotalUserOnline { get; set; }

    public Nullable<int> TotalOnline { get; set; }

    public Nullable<int> TotalClick { get; set; }

    public Nullable<byte> Flag { get; set; }

}

}
