
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_CustomerDeliveryAddress
{

    public int ID { get; set; }

    public Nullable<long> CustomerID { get; set; }

    public string Address { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public Nullable<int> IsMacdinh { get; set; }

    public string provinces { get; set; }

    public string districts { get; set; }

    public string wards { get; set; }

}

}
