
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ContactUs
{

    public long ContactID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string CellPhone { get; set; }

    public string HomePhone { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> Finished { get; set; }

    public Nullable<bool> ReadNew { get; set; }

    public string MessageContent { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> ReadDate { get; set; }

    public Nullable<System.DateTime> FinishDate { get; set; }

    public Nullable<byte> Status { get; set; }

}

}
