
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_CategoryMain
{

    public long MainCateID { get; set; }

    public string MainCateName { get; set; }

    public Nullable<int> Sort { get; set; }

    public string MainCateDesc { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public string MainCateIcon { get; set; }

    public string MainCateBanner { get; set; }

    public string Language { get; set; }

}

}
