
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_CategorySub2
{

    public long SubCate2ID { get; set; }

    public string SubCate2Name { get; set; }

    public Nullable<long> SubCate1ID { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public string SubCate2Desc { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> Sort { get; set; }

    public string Language { get; set; }

}

}
