
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_DeliverySelection
{

    public long DeliverySelectionID { get; set; }

    public string DeliveryName { get; set; }

    public string DeliveryDescription { get; set; }

    public Nullable<int> SortBy { get; set; }

    public Nullable<double> DeliveryCost { get; set; }

    public string Dichvuvanchuyen { get; set; }

    public string Dichvulapdat { get; set; }

    public Nullable<double> Totaldeposit { get; set; }

}

}
