
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Deposit
{

    public int DepositId { get; set; }

    public string DepositName { get; set; }

    public Nullable<double> Prices { get; set; }

    public Nullable<int> WishId { get; set; }

}

}
