
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_GroupCustomer
{

    public int GroupCusID { get; set; }

    public string GroupCusCode { get; set; }

    public string GroupCusName { get; set; }

    public string GroupCusDesc { get; set; }

    public Nullable<double> GroupCusValue { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> GroupCusCreate { get; set; }

}

}
