
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_HomeMainBanner
{

    public long HomeMainBannerID { get; set; }

    public string BannerPath { get; set; }

    public string BannerDescription { get; set; }

    public string BannerLandingpage { get; set; }

    public Nullable<System.DateTime> BannerUpload { get; set; }

    public string BannerHeader1 { get; set; }

    public string BannerHeader2 { get; set; }

    public Nullable<int> SortArr { get; set; }

}

}
