
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_LocalAccount
{

    public long LocalAccountID { get; set; }

    public string AccountCode { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }

    public Nullable<bool> Gender { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<long> PermissionID { get; set; }

    public string Avatar { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

}

}
