
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Product_Translation
{

    public int ProductID_EN { get; set; }

    public string ProductName_EN { get; set; }

    public string ShortDescription { get; set; }

    public string FullDescription_EN { get; set; }

    public Nullable<int> Idproduct { get; set; }

    public string PricePerBlock_EN { get; set; }

    public string PricePerDay_EN { get; set; }

    public string PricePerMonth_EN { get; set; }

    public string IdLanguage { get; set; }

    public string ProductSpecification { get; set; }

    public string ProductInstruction { get; set; }

}

}
