
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ProductTermConditionDetails
{

    public long PrDetailsId { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> WarehouseId { get; set; }

    public Nullable<double> CostInstallation { get; set; }

    public Nullable<double> CostDelivery { get; set; }

    public Nullable<double> CostInstallAndDelivery { get; set; }

    public Nullable<double> CostReservation { get; set; }

    public Nullable<double> CostDepositValue { get; set; }

    public Nullable<double> CostDepositDocument { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public string Tuvanchuyen { get; set; }

    public string Giaotannha { get; set; }

    public string Nhantratannha { get; set; }

    public string Giaovanhantratannha { get; set; }

    public string Tulapdat { get; set; }

    public string Huongdansudung { get; set; }

    public string Thotoilap { get; set; }

    public string Thotoithao { get; set; }

    public string Thodenlapvathao { get; set; }

}

}
