
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ProductPricePerDay
{

    public int PPDId { get; set; }

    public int ProductID { get; set; }

    public Nullable<double> Block1 { get; set; }

    public Nullable<double> Block2 { get; set; }

    public Nullable<double> Block3 { get; set; }

    public Nullable<double> Block4 { get; set; }

    public Nullable<double> Block5 { get; set; }

    public Nullable<double> Block6 { get; set; }

    public Nullable<double> Block7 { get; set; }

    public Nullable<double> Block8 { get; set; }

    public Nullable<double> Block9 { get; set; }

    public Nullable<double> Block10 { get; set; }

    public Nullable<double> Block11 { get; set; }

    public Nullable<double> Block12 { get; set; }

    public Nullable<double> Block13 { get; set; }

    public Nullable<double> Block14 { get; set; }

    public Nullable<double> Block15 { get; set; }

    public Nullable<double> Block16 { get; set; }

    public Nullable<double> Block17 { get; set; }

    public Nullable<double> Block18 { get; set; }

    public Nullable<double> Block19 { get; set; }

    public Nullable<double> Block20 { get; set; }

    public Nullable<double> Block21 { get; set; }

    public Nullable<double> Block22 { get; set; }

    public Nullable<double> Block23 { get; set; }

    public Nullable<double> Block24 { get; set; }

    public Nullable<double> Block25 { get; set; }

    public Nullable<double> Block26 { get; set; }

    public Nullable<double> Block27 { get; set; }

    public Nullable<double> Block28 { get; set; }

    public Nullable<double> Block29 { get; set; }

    public Nullable<double> Block30 { get; set; }

}

}
