
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Product
{

    public long ProductID { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string ProductAvatar { get; set; }

    public string ProductCity { get; set; }

    public string ProductDistrict { get; set; }

    public string ProductWard { get; set; }

    public string ShortDescription { get; set; }

    public string FullDescription { get; set; }

    public string ProductSpecification { get; set; }

    public string ProductInstruction { get; set; }

    public Nullable<int> StatusPercentage { get; set; }

    public Nullable<byte> StatusAvailability { get; set; }

    public string PricePerBlock { get; set; }

    public string PricePerDay { get; set; }

    public string PricePerMonth { get; set; }

    public Nullable<long> ProductMainCate { get; set; }

    public Nullable<long> ProductSubCate1 { get; set; }

    public Nullable<long> ProductSubCate2 { get; set; }

    public Nullable<long> ProductSubCate3 { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<double> ProductValue { get; set; }

    public string ListBy1 { get; set; }

    public string ListBy2 { get; set; }

    public string ListBy3 { get; set; }

    public string ListBy4 { get; set; }

    public string ListBy5 { get; set; }

    public string ListBy6 { get; set; }

    public string ListBy7 { get; set; }

    public string YoutubeLink { get; set; }

    public string Language { get; set; }

    public Nullable<int> Position { get; set; }

    public string Makho { get; set; }

    public Nullable<int> Hinhthucdatcoc { get; set; }

    public Nullable<int> Cocbangtienmat { get; set; }

    public Nullable<int> Cocbanggiayto { get; set; }

    public Nullable<int> Cocbanggiaytovahopdong { get; set; }

    public Nullable<double> Cocbanggiaytovahopdongprice { get; set; }

    public Nullable<int> Cocbangtaisan { get; set; }

    public Nullable<int> Soluongton { get; set; }

}

}
