
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ProductPricePerMonth
{

    public int PPMId { get; set; }

    public Nullable<int> ProductID { get; set; }

    public Nullable<double> Block1 { get; set; }

    public Nullable<double> Block2 { get; set; }

    public Nullable<double> Block3 { get; set; }

    public Nullable<double> Block4 { get; set; }

    public Nullable<double> Block5 { get; set; }

    public Nullable<double> Block6 { get; set; }

    public Nullable<double> Block7 { get; set; }

    public Nullable<double> Block8 { get; set; }

    public Nullable<double> Block9 { get; set; }

    public Nullable<double> Block10 { get; set; }

    public Nullable<double> Block11 { get; set; }

    public Nullable<double> Block12 { get; set; }

}

}
