
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Pre_Order
{

    public int pOrderId { get; set; }

    public Nullable<long> customerId { get; set; }

    public Nullable<long> productId { get; set; }

    public Nullable<int> status { get; set; }

    public Nullable<System.DateTime> createTime { get; set; }

    public Nullable<double> Totals { get; set; }

}

}
