
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_SiteMap
{

    public long SiteMapID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Contents { get; set; }

    public string Image { get; set; }

    public Nullable<byte> Status { get; set; }

    public string Kind { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<long> UpdateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string UrlFriendLy { get; set; }

    public string MetaTitle { get; set; }

    public string MetaDescription { get; set; }

    public string MetaKeyWord { get; set; }

    public string MetaImage { get; set; }

}

}
