
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_stockTempLog
{

    public int stockTempLogID { get; set; }

    public Nullable<int> stockTempId { get; set; }

    public Nullable<System.DateTime> createDate { get; set; }

    public Nullable<int> Qty { get; set; }

}

}
