
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_WareHouse
{

    public long whId { get; set; }

    public string WarehouseCode { get; set; }

    public string WarehouseName { get; set; }

    public string WarehouseAddress { get; set; }

    public string whOpenTime { get; set; }

    public string whCloseTime { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public Nullable<System.DateTime> createTime { get; set; }

    public string Images { get; set; }

    public string Policy { get; set; }

    public string Phone { get; set; }

    public string Zalo { get; set; }

    public string Messenger { get; set; }

    public string Skype { get; set; }

    public string Email { get; set; }

    public string Icons { get; set; }

    public string Hopdong { get; set; }

    public string ChinhSach { get; set; }

    public Nullable<System.DateTime> NgayTaoChinhSach { get; set; }

    public string BannerImage { get; set; }

    public string LocationMap { get; set; }

    public Nullable<int> LocalAccountID { get; set; }

}

}
