
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_WishList
{

    public long WishListID { get; set; }

    public long ProductID { get; set; }

    public long CustomerID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

}

}
