
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_WareHouse_Time
{

    public int whtid { get; set; }

    public Nullable<int> whId { get; set; }

    public string whOpenTime { get; set; }

    public string whCloseTime { get; set; }

    public string whOpenTime2 { get; set; }

    public string whCloseTime2 { get; set; }

    public string FromDayOfWeek { get; set; }

    public Nullable<int> ToDayOfWeek { get; set; }

    public string whOpenTime3 { get; set; }

    public string whCloseTime3 { get; set; }

    public string Title1 { get; set; }

    public string Title2 { get; set; }

    public string Title3 { get; set; }

}

}
