
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HirentWeb2022.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TimeBlock
{

    public int Id { get; set; }

    public string FromTime { get; set; }

    public string ToTime { get; set; }

    public string ForDays { get; set; }

    public Nullable<int> whId { get; set; }

    public Nullable<int> DisplayOrder { get; set; }

}

}
